# Build
FROM node:22 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build  # Compile
RUN npm prune --production  # Supprime les devDeps après la compilation

# Runtime
FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/src/docs ./src/docs
RUN mkdir -p public/covers
EXPOSE 3000
CMD ["node", "dist/server.js"]