services:
    mongodb:
        image: mongo:8
        container_name: novelya-mongodb-prod
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        volumes:
            - mongodb_prod_data:/data/db
            - ./src/config/init-db.js:/docker-entrypoint-initdb.d/init.js
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

volumes:
    mongodb_prod_data:
